# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ogstra.Proxor
PackageVersion: 1.6.13
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Ogstra/proxor/releases/download/v1.6.13/proxor-1.6.13-winget-x64.zip
    InstallerSha256: 2AA4831D9B9DD65AF0E4F342C44EC4B1AEE4DCC8A4ED287FB01F2E0AE89BB86C
    NestedInstallerFiles:
      - RelativeFilePath: proxor/proxor.exe
        PortableCommandAlias: proxor
ManifestType: installer
ManifestVersion: 1.12.0
